openapi: 3.0.0
openapi: 3.0.0
info:
  title: Ceremony2 User API
  version: 1.0.0
  description: |
    Unified user API endpoint for registration, login, password management, and phone verification.
    
    **All actions use POST** to `/requests/index.php?a=Users` with a JSON body containing an `endpoint` field and other required parameters.
servers:
  - url: /
paths:
  /requests/index.php?a=Users:
    post:
      summary: User API (register, login, forgetPassword, changePassword, sendCode, verifyCode)
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - endpoint
              properties:
                endpoint:
                  type: string
                  example: register
                  description: Action: register, login, forgetPassword, changePassword, sendCode, verifyCode
                fullName:
                  type: string
                  example: John Doe
                  description: Required for register
                email:
                  type: string
                  example: john@example.com
                  description: Required for register
                phone:
                  type: string
                  example: '1234567890'
                  description: Required for all actions except changePassword
                password:
                  type: string
                  example: secret123
                  description: Required for register/login
                oldPassword:
                  type: string
                  example: oldpass
                  description: Required for changePassword
                newPassword:
                  type: string
                  example: newpass
                  description: Required for changePassword
                code:
                  type: string
                  example: '123456'
                  description: Required for register/verifyCode/forgetPassword
      responses:
        '200':
          description: User API response (see endpoint for details)
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  error:
                    type: string
                    example: '0'
                  status:
                    type: string
                    example: successful
                  data:
                    oneOf:
                      - type: object
                        properties:
                          msg:
                            type: string
                            example: Login successful.
                          token:
                            type: string
                            example: abcdef123456...
                      - type: object
                        properties:
                          msg:
                            type: string
                            example: Verification code sent.
                      - type: object
                        properties:
                          msg:
                            type: string
                            example: Password changed.
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
