openapi: 3.0.0
info:
  title: 7yyak User API
  version: 1.0.0
  description: |
    Unified user API endpoint for registration, login, password management, and phone verification.
paths:
  /requests/index.php?a=Users:
    post:
      summary: Unified User API
      description: |
        All user actions (register, login, forgetPassword, changePassword, sendCode, verifyCode) are handled via the 'endpoint' parameter in the request body.
        Use the appropriate fields for each action as shown in the code samples below.
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - endpoint
              properties:
                endpoint:
                  type: string
                  description: Action to perform (register, login, sendCode, verifyCode, forgetPassword, changePassword)
                  example: register
                fullName:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john@example.com
                phone:
                  type: string
                  example: '1234567890'
                password:
                  type: string
                  example: secret123
                code:
                  type: string
                  example: '123456'
                oldPassword:
                  type: string
                  example: oldpass
                newPassword:
                  type: string
                  example: newpass
      responses:
        '200':
          description: User API response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  error:
                    type: string
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example: Success message
                      token:
                        type: string
                        example: abcdef123456...
      x-codeSamples:
        - lang: JSON
          label: Register
          source: |
            {
              "endpoint": "register",
              "fullName": "John Doe",
              "email": "john@example.com",
              "phone": "1234567890",
              "password": "secret123",
              "code": "123456"
            }
        - lang: JSON
          label: Login
          source: |
            {
              "endpoint": "login",
              "phone": "1234567890",
              "password": "secret123"
            }
        - lang: JSON
          label: Send Code
          source: |
            {
              "endpoint": "sendCode",
              "phone": "1234567890"
            }
        - lang: JSON
          label: Verify Code
          source: |
            {
              "endpoint": "verifyCode",
              "phone": "1234567890",
              "code": "123456"
            }
        - lang: JSON
          label: Forget Password
          source: |
            {
              "endpoint": "forgetPassword",
              "phone": "1234567890"
            }
        - lang: JSON
          label: Change Password
          source: |
            {
              "endpoint": "changePassword",
              "oldPassword": "oldpass",
              "newPassword": "newpass"
            }
                          msg:
                            type: string
                            example: Password changed.
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
