openapi: 3.0.0
info:
  title: 7yyak User API
  version: 1.0.0
  description: |
    Unified user API endpoint for registration, login, password management, and phone verification.
paths:
  /requests/index.php?a=Users&endpoint=register:
    post:
      summary: Register a new user
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [fullName, email, phone, password, code]
              properties:
                fullName:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john@example.com
                phone:
                  type: string
                  example: '1234567890'
                password:
                  type: string
                  example: secret123
      responses:
        '200':
          description: Registration response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  error:
                    type: string
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example: Registration successful.
      x-codeSamples:
        - lang: JSON
          label: Register
          source: |
            {
              "fullName": "John Doe",
              "email": "john@example.com",
              "phone": "1234567890",
              "password": "secret123",
            }

  /requests/index.php?a=Users&endpoint=login:
    post:
      summary: Login
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone, password]
              properties:
                phone:
                  type: string
                  example: '1234567890'
                password:
                  type: string
                  example: secret123
      responses:
        '200':
          description: Login response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  error:
                    type: string
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example: Login successful.
                      token:
                        type: string
                        example: abcdef123456...
      x-codeSamples:
        - lang: JSON
          label: Login
          source: |
            {
              "phone": "1234567890",
              "password": "secret123"
            }

  /requests/index.php?a=Users&endpoint=sendCode:
    post:
      summary: Send verification code
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone]
              properties:
                phone:
                  type: string
                  example: '1234567890'
      responses:
        '200':
          description: Send code response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  error:
                    type: string
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example: Verification code sent.
      x-codeSamples:
        - lang: JSON
          label: Send Code
          source: |
            {
              "phone": "1234567890"
            }

  /requests/index.php?a=Users&endpoint=verifyCode:
    post:
      summary: Verify code
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone, code]
              properties:
                phone:
                  type: string
                  example: '1234567890'
                code:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: Verify code response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  error:
                    type: string
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example: Code verified.
      x-codeSamples:
        - lang: JSON
          label: Verify Code
          source: |
            {
              "phone": "1234567890",
              "code": "123456"
            }

  /requests/index.php?a=Users&endpoint=forgetPassword:
    post:
      summary: Forget password
      description: Send a password reset code to the user's phone via WhatsApp.
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone]
              properties:
                phone:
                  type: string
                  example: '1234567890'
      responses:
        '200':
          description: Forget password response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  error:
                    type: string
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example: Password reset code sent.
      x-codeSamples:
        - lang: JSON
          label: Forget Password
          source: |
            {
              "phone": "1234567890"
            }

  /requests/index.php?a=Users&endpoint=changePassword:
    post:
      summary: Change password
      description: Change the user's password using bearer token authentication. Requires old and new password.
      tags: [User]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [oldPassword, newPassword]
              properties:
                oldPassword:
                  type: string
                  example: oldpass
                newPassword:
                  type: string
                  example: newpass
      responses:
        '200':
          description: Change password response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  error:
                    type: string
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example: Password changed.
      x-codeSamples:
        - lang: JSON
          label: Change Password
          source: |
            {
              "oldPassword": "oldpass",
              "newPassword": "newpass"
            }
                          msg:
                            type: string
                            example: Password changed.
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
